### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by gehnster** [wranders/ESISharp#40]
Is this project still active? Just curious because I'd love an ESI C# library written in .NET Core.

Thanks!

**Comment by eiaro** [comment]
If used with .NET Core, it should be rewritten to fit the current recommended styles and use the aspnet-contrib OAuth module for SSO. Just my humble opinion.

**Comment by wranders** [comment]
Yes, still active.
What reason are you wanting this to be in .NET Core?

I looked into writing it using Core, and even started, but got hung up because of Core missing things.
I thought about it and figured that the most likely reason someone would want this in Core is for ASP websites. There's already many completed ESI implementations using Python, JS, etc. that are well suited for a web environment. While it would be nice to have an entire site written in .NET, I think at this point in time, it would take away from things that need to happen.

**Comment by gehnster** [comment]
Reasons don't really matter, do they? Sounds like I got my answers though so thanks!
