### ISSUE TITLE
Sapmle project for WinForms

### ISSUE THREAD

**Issue by mrserikus** [wranders/ESISharp#41]
Is it possible to make any sample project for windows forms? I cant get normally working

**Comment by wranders** [comment]
A sample project is in the plan. 

I'm working on a substantial rewrite of the entire library since what's currently in `master` is a bit of a cluster at the moment, which is why many new paths haven't been added and some things might not be working.
I don't have an ETA since I have to squeeze dev time in where I can.

You can try to use [dev-restructure](../tree/dev-restructure) if you only need Public paths. That's currently all working (at least from my testing).
The source of your issues may be from the fact that `master` is essentially unmaintained at this point.
Authentication is what I'm trying to rework at the moment, so it's a bit flaky. Authenticated GET and POST requests *should* work, but I can't guarantee.
All PUT and DELETE methods will not work at the moment and will throw a `NotImplementedException`.
